language: c

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - zlib1g-dev
            - sqlite3
            - libsqlite3-dev
    - os: osx

compiler: gcc

script:
  - cd src
  - make